In [291]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
import glob

with open('data/competitions.json') as f:
    competitions = json.load(f)

In [292]:
# Women's World Cup ID is 72

wwc_id = 72

In [293]:
with open('data/matches/'+str(wwc_id)+'/30.json') as f:
    matches = json.load(f)

In [294]:
matches[0]

{'match_id': 69163,
 'match_date': '2019-06-24',
 'kick_off': '21:00:00.000',
 'competition': {'competition_id': 72,
  'country_name': 'International',
  'competition_name': "Women's World Cup"},
 'season': {'season_id': 30, 'season_name': '2019'},
 'home_team': {'home_team_id': 858,
  'home_team_name': "Sweden Women's",
  'home_team_gender': 'female',
  'home_team_group': None,
  'country': {'id': 220, 'name': 'Sweden'},
  'managers': [{'id': 3016,
    'name': 'Peter Gerhardsson',
    'nickname': None,
    'dob': None,
    'country': {'id': 220, 'name': 'Sweden'}}]},
 'away_team': {'away_team_id': 1206,
  'away_team_name': "Canada Women's",
  'away_team_gender': 'female',
  'away_team_group': None,
  'country': {'id': 40, 'name': 'Canada'},
  'managers': [{'id': 172,
    'name': 'Kenneth Heiner-MÃ¸ller',
    'nickname': None,
    'dob': '1971-01-17',
    'country': {'id': 61, 'name': 'Denmark'}}]},
 'home_score': 1,
 'away_score': 0,
 'match_status': 'available',
 'last_updated': '2020-07-29T05:00',
 'metadata': {'data_version': '1.1.0',
  'shot_fidelity_version': '2',
  'xy_fidelity_version': '2'},
 'match_week': 4,
 'competition_stage': {'id': 33, 'name': 'Round of 16'},
 'stadium': {'id': 154,
  'name': 'Parc des Princes',
  'country': {'id': 78, 'name': 'France'}},
 'referee': {'id': 1640, 'name': 'K. Jacewicz'}}

In [295]:
df = pd.DataFrame(matches)

df.head(2)

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,last_updated,metadata,match_week,competition_stage,stadium,referee
0,69163,2019-06-24,21:00:00.000,"{'competition_id': 72, 'country_name': 'Intern...","{'season_id': 30, 'season_name': '2019'}","{'home_team_id': 858, 'home_team_name': 'Swede...","{'away_team_id': 1206, 'away_team_name': 'Cana...",1,0,available,2020-07-29T05:00,"{'data_version': '1.1.0', 'shot_fidelity_versi...",4,"{'id': 33, 'name': 'Round of 16'}","{'id': 154, 'name': 'Parc des Princes', 'count...","{'id': 1640, 'name': 'K. Jacewicz'}"
1,68346,2019-06-20,18:00:00.000,"{'competition_id': 72, 'country_name': 'Intern...","{'season_id': 30, 'season_name': '2019'}","{'home_team_id': 1208, 'home_team_name': 'Came...","{'away_team_id': 1215, 'away_team_name': 'New ...",2,1,available,2020-07-29T05:00,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 1, 'name': 'Regular Season'}",NaN,NaN

In [296]:
def dict_split(d, col):
    return d[col].apply(pd.Series)

cols = ['home_team', 'away_team', 'competition_stage']


for c in cols:
    a = dict_split(df, c)
    df = pd.concat([df, a], axis=1)
    df.drop(c, axis=1, inplace=True)

df.columns

Index(['match_id', 'match_date', 'kick_off', 'competition', 'season',
       'home_score', 'away_score', 'match_status', 'last_updated', 'metadata',
       'match_week', 'stadium', 'referee', 'home_team_id', 'home_team_name',
       'home_team_gender', 'home_team_group', 'country', 'managers',
       'away_team_id', 'away_team_name', 'away_team_gender', 'away_team_group',
       'country', 'managers', 'id', 'name'],
      dtype='object')

In [297]:
df.drop(['competition', 'season', 'match_status','metadata', 'last_updated'], axis=1, inplace=True)

df.head()

,match_id,match_date,kick_off,home_score,away_score,match_week,stadium,referee,home_team_id,home_team_name,...,country,managers,away_team_id,away_team_name,away_team_gender,away_team_group,country,managers,id,name
0,69163,2019-06-24,21:00:00.000,1,0,4,"{'id': 154, 'name': 'Parc des Princes', 'count...","{'id': 1640, 'name': 'K. Jacewicz'}",858,Sweden Women's,...,"{'id': 220, 'name': 'Sweden'}","[{'id': 3016, 'name': 'Peter Gerhardsson', 'ni...",1206,Canada Women's,female,None,"{'id': 40, 'name': 'Canada'}","[{'id': 172, 'name': 'Kenneth Heiner-MÃ¸ller',...",33,Round of 16
1,68346,2019-06-20,18:00:00.000,2,1,3,NaN,NaN,1208,Cameroon Women's,...,"{'id': 39, 'name': 'Cameroon'}","[{'id': 4350, 'name': 'Alain Djeumfa', 'nickna...",1215,New Zealand Women's,female,Group E,"{'id': 163, 'name': 'New Zealand'}","[{'id': 130, 'name': 'Tom Sermanni', 'nickname...",1,Regular Season
2,68355,2019-06-22,17:30:00.000,3,0,4,NaN,NaN,857,Germany Women's,...,"{'id': 85, 'name': 'Germany'}",NaN,1213,Nigeria Women's,female,Group A,"{'id': 166, 'name': 'Nigeria'}",NaN,1,Regular Season
3,69301,2019-07-06,17:00:00.000,1,2,7,"{'id': 162, 'name': 'Allianz Riviera', 'countr...","{'id': 745, 'name': 'A. Pustovoitova'}",865,England Women's,...,"{'id': 68, 'name': 'England'}","[{'id': 3464, 'name': 'Phil Neville', 'nicknam...",858,Sweden Women's,female,None,"{'id': 220, 'name': 'Sweden'}","[{'id': 3016, 'name': 'Peter Gerhardsson', 'ni...",25,3rd Place Final
4,68311,2019-06-18,21:00:00.000,1,4,3,NaN,NaN,1212,Jamaica Women's,...,"{'id': 113, 'name': 'Jamaica'}","[{'id': 4243, 'name': 'Hue Menzies', 'nickname...",1205,Australia Women's,female,Group C,"{'id': 14, 'name': 'Australia'}","[{'id': 3541, 'name': 'Ante Milicic', 'nicknam...",1,Regular Season

In [298]:
df.drop(['stadium', 'referee'], axis=1, inplace=True)
df.columns

Index(['match_id', 'match_date', 'kick_off', 'home_score', 'away_score',
       'match_week', 'home_team_id', 'home_team_name', 'home_team_gender',
       'home_team_group', 'country', 'managers', 'away_team_id',
       'away_team_name', 'away_team_gender', 'away_team_group', 'country',
       'managers', 'id', 'name'],
      dtype='object')

In [299]:
names = ['match_id', 'match_date', 'kick_off', 'home_score', 'away_score', 'match_week', 'home_team_id',
        'home_team_name', 'home_team_gender', 'home_team_group', 'home_team_country',
        'home_team_managers', 'away_team_id', 'away_team_name', 'away_team_gender',
        'away_team_group', 'away_team_country', 'away_team_managers', 'competition_stage_id',
        'competition_stage_name']

df.columns = names

df.drop(['home_team_gender', 'away_team_gender', 'home_team_country', 
         'away_team_country', 'home_team_managers', 'away_team_managers'], axis=1, inplace=True)

df.head(2)

,match_id,match_date,kick_off,home_score,away_score,match_week,home_team_id,home_team_name,home_team_group,away_team_id,away_team_name,away_team_group,competition_stage_id,competition_stage_name
0,69163,2019-06-24,21:00:00.000,1,0,4,858,Sweden Women's,None,1206,Canada Women's,None,33,Round of 16
1,68346,2019-06-20,18:00:00.000,2,1,3,1208,Cameroon Women's,Group E,1215,New Zealand Women's,Group E,1,Regular Season

In [300]:
df['home_team_name'].unique()

array(["Sweden Women's", "Cameroon Women's", "Germany Women's",
       "England Women's", "Jamaica Women's", "Italy Women's",
       "France Women's", "Japan Women's", "Korea Republic Women's",
       "United States Women's", "Norway Women's", "China PR Women's",
       "Spain Women's", "Australia Women's", "Brazil Women's",
       "Canada Women's", "Argentina Women's", "New Zealand Women's",
       "Chile Women's", "Nigeria Women's", "South Africa Women's",
       "Netherlands Women's", "Scotland Women's", "Thailand Women's"],
      dtype=object)

In [301]:
df['home_team_name'] = df['home_team_name'].str.replace(" Women's", '')

df['home_team_name'].unique()

array(['Sweden', 'Cameroon', 'Germany', 'England', 'Jamaica', 'Italy',
       'France', 'Japan', 'Korea Republic', 'United States', 'Norway',
       'China PR', 'Spain', 'Australia', 'Brazil', 'Canada', 'Argentina',
       'New Zealand', 'Chile', 'Nigeria', 'South Africa', 'Netherlands',
       'Scotland', 'Thailand'], dtype=object)

In [302]:
df['away_team_name'] = df['away_team_name'].str.replace(" Women's", '')

df['away_team_name'].unique()

array(['Canada', 'New Zealand', 'Nigeria', 'Sweden', 'Australia',
       'Netherlands', 'Brazil', 'Scotland', 'Thailand', 'England',
       'Norway', 'Chile', 'Spain', 'Korea Republic', 'China PR',
       'South Africa', 'Italy', 'Jamaica', 'Cameroon', 'Japan',
       'United States', 'Argentina', 'France', 'Germany'], dtype=object)

In [303]:
df.head()

,match_id,match_date,kick_off,home_score,away_score,match_week,home_team_id,home_team_name,home_team_group,away_team_id,away_team_name,away_team_group,competition_stage_id,competition_stage_name
0,69163,2019-06-24,21:00:00.000,1,0,4,858,Sweden,None,1206,Canada,None,33,Round of 16
1,68346,2019-06-20,18:00:00.000,2,1,3,1208,Cameroon,Group E,1215,New Zealand,Group E,1,Regular Season
2,68355,2019-06-22,17:30:00.000,3,0,4,857,Germany,Group B,1213,Nigeria,Group A,1,Regular Season
3,69301,2019-07-06,17:00:00.000,1,2,7,865,England,None,858,Sweden,None,25,3rd Place Final
4,68311,2019-06-18,21:00:00.000,1,4,3,1212,Jamaica,Group C,1205,Australia,Group C,1,Regular Season

In [306]:
df[df['home_team_name'] == 'Netherlands']

,match_id,match_date,kick_off,home_score,away_score,match_week,home_team_id,home_team_name,home_team_group,away_team_id,away_team_name,away_team_group,competition_stage_id,competition_stage_name
37,22964,2019-06-15,15:00:00.000,3,1,2,851,Netherlands,Group E,1208,Cameroon,Group E,1,Regular Season
43,68344,2019-06-20,18:00:00.000,2,1,3,851,Netherlands,Group E,1206,Canada,Group E,1,Regular Season
48,69188,2019-06-25,21:00:00.000,2,1,4,851,Netherlands,None,1210,Japan,None,33,Round of 16
51,69284,2019-07-03,21:00:00.000,1,0,6,851,Netherlands,None,858,Sweden,None,15,Semi-finals

In [307]:
# Netherlands team ID

neth_id = 851